[alembic]
script_location = fastapi_app/alembic
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic
level = INFO
handlers =
qualname = alembic

[handlers]
keys =

[formatters]
keys =

[logger_root]
level = INFO
handlers =

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[logger_sqlalchemy]
level = INFO
handlers =
qualname = sqlalchemy

[DEFAULT]
sqlalchemy.url = ${DATABASE_URL}

