# Generated by Django 5.1.2 on 2026-03-18 19:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, default='', max_length=2048)),
                ('content_type', models.CharField(blank=True, default='', max_length=127)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.card')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('json', 'JSON')], default='text', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='core.space')),
            ],
            options={
                'unique_together': {('space', 'key')},
            },
        ),
        migrations.CreateModel(
            name='CardMovementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('moved', 'Moved'), ('created', 'Created'), ('updated', 'Updated')], default='moved', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_events', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_events', to='core.card')),
                ('from_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_events', to='core.column')),
                ('from_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_events', to='core.track')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_movement_events', to='core.organization')),
                ('to_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_events', to='core.column')),
                ('to_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_events', to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='CardFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='core.card')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.cardfielddefinition')),
            ],
            options={
                'unique_together': {('card', 'definition')},
            },
        ),
        migrations.CreateModel(
            name='CardRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('depends_on', 'Depends on'), ('related_to', 'Related to'), ('blocked_by', 'Blocked by')], default='related_to', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_relations', to='core.card')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_relations', to='core.organization')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_relations', to='core.card')),
            ],
            options={
                'unique_together': {('from_card', 'to_card', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='WipLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('column', 'Column'), ('track', 'Track')], max_length=16)),
                ('limit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_limits', to='core.board')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.column')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_limits', to='core.organization')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
            options={
                'unique_together': {('organization', 'board', 'scope_type', 'column', 'track')},
            },
        ),
    ]
