# Generated by Django 5.1.2 on 2026-03-18 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_cardblock_cardfielddefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_type', models.CharField(choices=[('previous_path', 'Previous path'), ('not_completed_checklists', 'Not completed checklists'), ('unfinished_children', 'Unfinished children'), ('exceeded_wip', 'Exceeded WIP')], max_length=64)),
                ('deny_action', models.CharField(choices=[('move_card', 'Deny moving card'), ('create_card', 'Deny creating card')], default='move_card', max_length=32)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restriction_rules', to='core.board')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restriction_rules', to='core.organization')),
                ('to_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_destination_restrictions', to='core.column')),
            ],
            options={
                'indexes': [models.Index(fields=['board', 'to_column', 'condition_type'], name='core_restri_board_i_1b906d_idx')],
            },
        ),
    ]
