# Generated by Django 5.1.2 on 2026-03-18 19:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_automationrule_automationexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='estimate_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='planned_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='planned_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(blank=True, default='', max_length=1000)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='core.board')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SprintCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='core.sprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_capacities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['organization', 'board', 'start_at', 'end_at'], name='core_sprint_organiz_147c03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('organization', 'board', 'name', 'start_at', 'end_at')},
        ),
        migrations.AlterUniqueTogether(
            name='sprintcapacity',
            unique_together={('sprint', 'user')},
        ),
    ]
