# Generated by Django 5.1.2 on 2026-03-18 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicedeskslapolicy_ticket_ticketcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_comments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.card')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_comments', to='core.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
